import type { Metadata } from "next";
import { Geist, Geist_Mono, Chiron_GoRound_TC } from "next/font/google";
import "./globals.css";


const chiron = Chiron_GoRound_TC({
  weight: "400",
  variable: "--font-chiron",
  subsets: [],
  display:'swap',
  preload: false,
  fallback: ["sans-serif"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${chiron.className} ${chiron.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
