import type { Metadata } from "next";
import { Geist, Geist_Mono, Chiron_GoRound_TC } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const chiron = Chiron_GoRound_TC({
  variable: "--font-chiron",
  subsets: ["latin"],
  fallback: ["sans-serif"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kor">
      <body
        className={`${chiron.className} ${chiron.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
