import type { Metadata } from "next";
import { Geist, Geist_Mono, Chiron_GoRound_TC } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/app/components/theme-provider";

const chiron = Chiron_GoRound_TC({
  weight: "400",
  variable: "--font-chiron",
  subsets: [],
  display: 'swap',
  preload: false,
  fallback: ["sans-serif"],
})

export const metadata: Metadata = {
  title: "PEECEMAKER",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/favicon.ico",
      href: "/favicon.ico",
    },
    shortcut: '/favicon.ico',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${chiron.className} ${chiron.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
          disableTransitionOnChange
        >{children}</ThemeProvider>

      </body>
    </html>
  );
}
